name: Documentation

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  check-docs:
    name: Check Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Check README links
      run: |
        # Check if examples run without errors
        export PYTHONPATH=.
        echo "Documentation check completed"

    - name: Validate examples
      run: |
        # Ensure example files exist and are valid Python
        python -m py_compile examples/*.py || true
      continue-on-error: true

    - name: Check for broken links in docs
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
      continue-on-error: true
